name: Build and Deploy Presentation

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-deploy:
    uses: IndrajeetPatil/workflows/.github/workflows/build-presentation-r.yaml@main
    with:
      runner-os: macos-latest
    permissions:
      contents: read
      pages: write
      id-token: write
